author: Parsa Yazdi
description: Structural Engineering Consultant
show_excerpts: true

# generate social links in footer
social_links:
  - { platform: github,         user_url: "https://github.com/jekyll/someparsa" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/parsayazdi" }
  - { platform: twitter,        user_url: "https://twitter.com/someparsa" }

# Build settings
theme: minima
