theme: jekyll-theme-minimal
title: Parsa Yazdi
subtitle: Structural Engineer + Software Developer
description: Here I list the links and the content that I want to share with you.

social-network-links:
  email: "parsa.yazdi@gmail.com"
  github: someparsa
  twitter: someparsa
  linkedin: parsayazdi
  ORCID: 0000-0002-5086-1701
#  google-scholar: your google scholar
